FROM icytower-base-win32

WORKDIR /app

COPY src src/
COPY win32 win32/

ADD https://github.com/liballeg/allegro5/releases/download/5.2.11.2/allegro-x86_64-w64-mingw32-gcc-15.2.0-posix-seh-static-5.2.11.2.zip allegro.zip
ADD https://github.com/liballeg/allegro5/releases/download/5.2.11.2/allegro_deps-x86_64-w64-mingw32-gcc-15.2.0-posix-seh-1.16.0.zip allegro_deps.zip

RUN unzip allegro.zip -d src
RUN unzip allegro_deps.zip -d src

RUN ./win32/build.sh

RUN cd install/bin && zip -r ../../icytower.zip .
